theme: jekyll-theme-minimal
title: Corentin Kervadec
description: PhD Student @ INSA Lyon & Orange.
logo: pic2.png
twitter: https://twitter.com/CorentK
email: mailto:corentin.kervadec@orange.com
scholar: https://scholar.google.fr/citations?user=Rx507eQAAAAJ&hl
