theme: jekyll-theme-minimal
title: Corentin Kervadec
description: Postdoctoral researcher @ UPF || PhD in Machine Learning.
interest: Artificial Intelligence, Large Language Models.
logo: pic4.png
mail: mailto:corentin.kervadec@gmail.com
scholar: https://scholar.google.fr/citations?user=Rx507eQAAAAJ&hl
cv: cv_Kervadec.pdf 
plugins:
  - jemoji


