theme: jekyll-theme-minimal
title: Corentin Kervadec
description: Postdoctoral researcher @ UPF || PhD in Machine Learning.
interest: Interested in improving our understanding of how artificial networks work.
logo: pic4.png
twitter: https://twitter.com/CorentK
mail: mailto:corentin.kervadec@gmail.com
scholar: https://scholar.google.fr/citations?user=Rx507eQAAAAJ&hl
cv: cv_Kervadec.pdf 
plugins:
  - jemoji


