theme: jekyll-theme-minimal
title: Hello!
# description: Postdoctoral researcher @ UPF, Barcelona.
# interest: Artificial Intelligence, Large Language Models.
logo: pic4.png
mail: mailto:corentin.kervadec@gmail.com
scholar: https://scholar.google.fr/citations?user=Rx507eQAAAAJ&hl
cv: "/cv.html" 
plugins:
  - jemoji


